name: pfp_env
channels:
  - conda-forge
dependencies:
  - python=3
  - cftime
  - configobj
  - python-dateutil
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pyqt
  - pytz
  - scipy
  - statsmodels
  - timezonefinder
  - xlwt
  - xlrd
  - xlsxwriter
